[package]
name = "words_of_wisdom_tcp"
version = "0.1.0"
authors = ["Viachslau Rouski"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
rand = "0.8.5"